language: rust
dist: trusty
rust:
- stable

cache: cargo

script:
  # It's a net time gain on Travis to build the tests in release mode.
  - |
      mkdir /tmp/tmpfs &&
      sudo mount none /tmp/tmpfs -t tmpfs &&
      cargo build --release &&
      TMPDIR=/tmp/tmpfs cargo test --release
