language: rust
dist: trusty
rust:
- stable

cache: cargo

script:
  # It's a net time gain on Travis to build the tests in release mode.
  - |
      sudo mount none /tmp -t tmpfs &&
      cargo build --release &&
      cargo test --release
