[package]
name = "crymap"
version = "0.1.0"
authors = ["Jason Lingle <jason@lin.gl>"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
base64 = "0.12"
bit-set = "0.5"
byteorder = "1.3"
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33"
fern = "0.6"
lazy_static = "1.4"
log = "0.4.8"
nix = "0.17"
notify = "5.0.0-pre.2"
openssl = "0.10.29"
rand = "0.7"
regex = "1.3"
rpassword = "4.0"
rayon = "1.3"
rust-argon2 = "0.8"
secstr = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = "0.11"
serde_repr = "0.1"
syslog = "5.0"
tempfile = "3.1"
thiserror = "1.0"
tiny-keccak = { version = "2.0", features = ["sha3", "kmac"] }
toml = "0.5"
zstd = "0.5"

[dev-dependencies]
proptest = "0.10"
